### ISSUE TITLE
Please create release in github

### ISSUE THREAD

**Issue by cyberman54** [lewisxhe/AXP202X_Library#12]
@lewisxhe Please create releases in in github to trigger update library on platformio.org, thanks.

**Comment by lewisxhe** [comment]
I still don't want to post it now, it should be a test that is not perfect and complete. @cyberman54

**Comment by cyberman54** [comment]
Suggestion: You can mark releases in github as pre-release.

**Comment by lewisxhe** [comment]
As you wish, I pre-released the first edition. @cyberman54
