### ISSUE TITLE
AXP192 on T-Beam V1.0 charge current control settings seems not work

### ISSUE THREAD

**Issue by fafu** [lewisxhe/AXP202X_Library#18]
When using the newly introduced charge current control settings to any setting (according to getChargeControl() is on AXP1XX_CHARGE_CUR_450MA) then the getBattDischargeCurrent is reporting it is not charging. Even setting setChargeControlCur(AXP1XX_CHARGE_CUR_450MA) to the previously read value with getChargeControl() seems to cause this issue.

**Comment by cyberman54** [comment]
@lewisxhe I made PR to solve this. After merging, could you please increase release version number? Needed for platform.io, thanks.

**Comment by cyberman54** [comment]
@fafu A bug in `setChargeControlCur()` inadvertantly sets the charging enable control bit to zero. Thus, whenever the method is called, charge current is set, but charging is disabled. That's why you get report "not charging" after. My PR fixes this.

**Comment by lewisxhe** [comment]
Thanks @cyberman54

**Comment by fafu** [comment]
Hi both,
tested the PR on my local T-Beam 1.0 (equipped with a AXP192) - I could verify setting the same value as the previous read value is successful. A second test with a max charge current of 100mA was also successfully. Using the max charge current of 1000mA worked - but I only saw a max charge current of ~400mA but maybe this originates in my setup. This issue seems to be solved. Thank you.
