### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by clow57** [lewisxhe/AXP202X_Library#3]
Apologies as this is a more general T-watch question. I am trying to understand the circuit for the AXP202. I know that LDO3 is for the main chip, and LDO2 is for the display, but I don't know what the other LDOs power. DO you guys have a full schematic?

Thanks
Chris

**Comment by cyberman54** [comment]
I would need this, too, to develop my software.

**Comment by cyberman54** [comment]
@clow57 LDO3 ist not main chip, but GPS chip. LDO2 is LORA chip. DCDC1 is OLED display.

as stated here: https://github.com/lewisxhe/TTGO-T-Beam

**Comment by lewisxhe** [comment]
@clow57 
LDO3: s76g/s78g chip power supply [controllable, 3.3V voltage required]
LDO4: s76g/s78g GPS circuit power supply [controllable, 1.8V voltage required]

**Comment by lewisxhe** [comment]
Close the problem here, if there are still problems, please reopen
