### ISSUE TITLE
Basic schematic of this chip

### ISSUE THREAD

**Issue by Gruniek** [lewisxhe/AXP202X_Library#30]
Hi,

Quick question, did you have a basic schematic of this chip for connect to just :

- 1 Lipo 1S
- 1 Vin by USB
- esp32 in 3.3V 
- I2C connection 
- 1 power on/off/key

I found the datasheet but it's not explicit for the basic use.

Thanks a lot !

**Comment by lewisxhe** [comment]
Please refer to the design manual
