### ISSUE TITLE
Publish library on platformio

### ISSUE THREAD

**Issue by cyberman54** [lewisxhe/AXP202X_Library#4]
Please publish this library on platformio platform:

https://platformio.org/lib

https://docs.platformio.org/en/latest/librarymanager/creating.html

**Comment by cyberman54** [comment]
I registered it for you on platformio, it now awaits moderation.

**Comment by lewisxhe** [comment]
Ok, thanks!

**Comment by cyberman54** [comment]
Done:

https://platformio.org/lib/show/6657/AXP202X_Library/
