### ISSUE TITLE
Bus Invalid State on  axp.begin(Wire, AXP192_SLAVE_ADDRESS) 

### ISSUE THREAD

**Issue by floki-92** [lewisxhe/AXP202X_Library#42]
Hi,
I`m on ESP32 Sim800 TT-Go SIM800C AXP192 20200609.
Sometimes i get the error below when calling ```axp.begin(Wire, AXP192_SLAVE_ADDRESS)```: 
```
[E][esp32-hal-i2c.c:1426] i2cCheckLineState(): Bus Invalid State, TwoWire() Can't init sda=1, scl=0
chip id detect 0x0
AXP Power begin failed
```
This also happens with the original example code from https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM. 

Questions:
1. Any hint or clue what's causing the issue & how to fix it? Without battery monitoring it's pretty risky to put the unit outside.. If i press PWR 2 seconds i can fix it temporarly, but question then would be how to fix it on the field without physical access?

**Comment by cyberman54** [comment]
Check if there are any other components on same i2c bus. They may block the bus, if powered off. Also, check pull-up resistors on ic2 bus.

**Comment by lewisxhe** [comment]
This is an I2C line failure
