### ISSUE TITLE
Arduino Library Registry

### ISSUE THREAD

**Issue by r41d** [lewisxhe/AXP202X_Library#45]
Hello there :)

Have you considered submitting this library to the official Arduino Library Registry? (https://github.com/arduino/library-registry)

That way, this library could easily be installed in the Arduino IDE via the built-in Library Manager.

As far as I can tell everything in the `library.properties` file of this library already looks great, the only thing that would be necessary would be a PR on the registry repo and setting a git tag (https://github.com/arduino/library-registry/blob/main/FAQ.md#submission-requirements)

**Comment by lewisxhe** [comment]
I have submitted a request to the `library-registry`.

https://github.com/arduino/library-registry/pull/1397

**Comment by r41d** [comment]
Awesome, thanks for responding quickly :)
