### ISSUE TITLE
getVbusCurrent() and getVbusVoltage() not working

### ISSUE THREAD

**Issue by cyberman54** [lewisxhe/AXP202X_Library#7]
Methods `getVbusCurrent()` and `getVbusVoltage()` are not working on T-Beam V1.0, result values are always zero while VBUS is present. I would expect to get USB voltage and current values while USB is plugged.

I checked schematic, AXP192 and AXP202 datasheets and code of library, but can't catch the problem. Need help.

**Comment by lewisxhe** [comment]
You must first enable adc
```
axp.adc1Enable(AXP202_VBUS_VOL_ADC1, 1);
axp.adc1Enable(AXP202_VBUS_CUR_ADC1, 1);
```
@cyberman54

**Comment by cyberman54** [comment]
Works!
Thanks for the hint.
